  
- name: Log into private registry
  shell: docker login -u {{container_reg_usr}} -p {{container_reg_pass}} trackerapp.azurecr.io 

- name: remove all docker containers
  shell: docker rm -f $(docker ps -a -q) 
  ignore_errors: true
   
- name: remove all docker images
  shell: docker rmi $(docker images -q) -f
  ignore_errors: true
         
- name: Create env file for weight tracker app
  template:
    src: /home/{{ ansible_user }}/ansible-agent/roles/app_deploy/templates/env.j2
    dest: /home/{{ ansible_user }}/.env
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: '0644'       

- name: pull container form azure private registry
  shell: docker pull trackerapp.azurecr.io/{{image_version}}    
   
- name: run container
  shell: docker run --restart=always --env-file .env --name trackerapp  -d  -p 8080:8080 trackerapp.azurecr.io/{{image_version}}     
    

- name: Init postgres DB 
  command: docker exec trackerapp npm run initdb
  run_once: true  

  
